"""
Reset CSV files with sample metro network data.
This script initializes or resets the metro system with a comprehensive sample network.
"""

import csv


def reset_stations_csv():
    """Create a comprehensive metro network with multiple lines and interchanges."""
    with open('stations.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['name', 'lines', 'neighbours'])
        
        # Red Line stations
        writer.writerow(['Airport', 'Red', 'Aerocity:Red'])
        writer.writerow(['Aerocity', 'Red', 'Airport:Red;Mahipalpur:Red'])
        writer.writerow(['Mahipalpur', 'Red', 'Aerocity:Red;Vasant Kunj:Red'])
        writer.writerow(['Vasant Kunj', 'Red', 'Mahipalpur:Red;Saket:Red'])
        writer.writerow(['Saket', 'Red;Yellow', 'Vasant Kunj:Red;Hauz Khas:Red;Malviya Nagar:Yellow'])
        writer.writerow(['Hauz Khas', 'Red;Yellow', 'Saket:Red;Green Park:Red;IIT:Yellow'])
        writer.writerow(['Green Park', 'Red', 'Hauz Khas:Red;AIIMS:Red'])
        writer.writerow(['AIIMS', 'Red;Yellow', 'Green Park:Red;INA:Red;Safdarjung:Yellow'])
        writer.writerow(['INA', 'Red', 'AIIMS:Red;Central Secretariat:Red'])
        writer.writerow(['Central Secretariat', 'Red;Yellow', 'INA:Red;Patel Chowk:Red;Udyog Bhawan:Yellow'])
        writer.writerow(['Patel Chowk', 'Red', 'Central Secretariat:Red;Rajiv Chowk:Red'])
        writer.writerow(['Rajiv Chowk', 'Red;Blue;Yellow', 'Patel Chowk:Red;New Delhi:Red;Barakhamba:Blue;Palika Bazaar:Yellow'])
        writer.writerow(['New Delhi', 'Red;Orange', 'Rajiv Chowk:Red;Chawri Bazar:Red;Shivaji Stadium:Orange'])
        writer.writerow(['Chawri Bazar', 'Red', 'New Delhi:Red;Chandni Chowk:Red'])
        writer.writerow(['Chandni Chowk', 'Red', 'Chawri Bazar:Red;Kashmere Gate:Red'])
        writer.writerow(['Kashmere Gate', 'Red;Yellow', 'Chandni Chowk:Red;Shastri Nagar:Red;Civil Lines:Yellow'])
        writer.writerow(['Shastri Nagar', 'Red', 'Kashmere Gate:Red;Tis Hazari:Red'])
        writer.writerow(['Tis Hazari', 'Red', 'Shastri Nagar:Red;Pul Bangash:Red'])
        writer.writerow(['Pul Bangash', 'Red', 'Tis Hazari:Red;Pratap Nagar:Red'])
        writer.writerow(['Pratap Nagar', 'Red', 'Pul Bangash:Red;Shastri Park:Red'])
        writer.writerow(['Shastri Park', 'Red', 'Pratap Nagar:Red;Seelampur:Red'])
        writer.writerow(['Seelampur', 'Red', 'Shastri Park:Red;Welcome:Red'])
        writer.writerow(['Welcome', 'Red', 'Seelampur:Red'])
        
        # Blue Line stations
        writer.writerow(['Dwarka', 'Blue', 'Dwarka Mor:Blue'])
        writer.writerow(['Dwarka Mor', 'Blue', 'Dwarka:Blue;Nawada:Blue'])
        writer.writerow(['Nawada', 'Blue', 'Dwarka Mor:Blue;Uttam Nagar:Blue'])
        writer.writerow(['Uttam Nagar', 'Blue', 'Nawada:Blue;Janakpuri West:Blue'])
        writer.writerow(['Janakpuri West', 'Blue', 'Uttam Nagar:Blue;Janakpuri East:Blue'])
        writer.writerow(['Janakpuri East', 'Blue', 'Janakpuri West:Blue;Tilak Nagar:Blue'])
        writer.writerow(['Tilak Nagar', 'Blue', 'Janakpuri East:Blue;Subhash Nagar:Blue'])
        writer.writerow(['Subhash Nagar', 'Blue', 'Tilak Nagar:Blue;Tagore Garden:Blue'])
        writer.writerow(['Tagore Garden', 'Blue', 'Subhash Nagar:Blue;Rajouri Garden:Blue'])
        writer.writerow(['Rajouri Garden', 'Blue;Pink', 'Tagore Garden:Blue;Ramesh Nagar:Blue;Mayapuri:Pink'])
        writer.writerow(['Ramesh Nagar', 'Blue', 'Rajouri Garden:Blue;Moti Nagar:Blue'])
        writer.writerow(['Moti Nagar', 'Blue', 'Ramesh Nagar:Blue;Kirti Nagar:Blue'])
        writer.writerow(['Kirti Nagar', 'Blue;Green', 'Moti Nagar:Blue;Shadipur:Blue;Satguru Ram Singh:Green'])
        writer.writerow(['Shadipur', 'Blue', 'Kirti Nagar:Blue;Patel Nagar:Blue'])
        writer.writerow(['Patel Nagar', 'Blue', 'Shadipur:Blue;Rajendra Place:Blue'])
        writer.writerow(['Rajendra Place', 'Blue', 'Patel Nagar:Blue;Karol Bagh:Blue'])
        writer.writerow(['Karol Bagh', 'Blue', 'Rajendra Place:Blue;RK Ashram:Blue'])
        writer.writerow(['RK Ashram', 'Blue', 'Karol Bagh:Blue;Barakhamba:Blue'])
        writer.writerow(['Barakhamba', 'Blue', 'RK Ashram:Blue;Rajiv Chowk:Blue'])
        writer.writerow(['Mandi House', 'Blue;Violet', 'Barakhamba:Blue;Pragati Maidan:Blue;ITO:Violet'])
        writer.writerow(['Pragati Maidan', 'Blue', 'Mandi House:Blue;Indraprastha:Blue'])
        writer.writerow(['Indraprastha', 'Blue', 'Pragati Maidan:Blue;Yamuna Bank:Blue'])
        writer.writerow(['Yamuna Bank', 'Blue', 'Indraprastha:Blue;Akshardham:Blue'])
        writer.writerow(['Akshardham', 'Blue', 'Yamuna Bank:Blue;Mayur Vihar:Blue'])
        writer.writerow(['Mayur Vihar', 'Blue;Pink', 'Akshardham:Blue;Mayur Vihar Ext:Blue;Mayur Vihar Pocket:Pink'])
        writer.writerow(['Mayur Vihar Ext', 'Blue', 'Mayur Vihar:Blue;Noida Sector 15:Blue'])
        writer.writerow(['Noida Sector 15', 'Blue', 'Mayur Vihar Ext:Blue;Noida Sector 16:Blue'])
        writer.writerow(['Noida Sector 16', 'Blue', 'Noida Sector 15:Blue;Noida Sector 18:Blue'])
        writer.writerow(['Noida Sector 18', 'Blue', 'Noida Sector 16:Blue;Botanical Garden:Blue'])
        writer.writerow(['Botanical Garden', 'Blue;Magenta', 'Noida Sector 18:Blue;Noida Golf Course:Blue;Okhla Bird Sanctuary:Magenta'])
        writer.writerow(['Noida Golf Course', 'Blue', 'Botanical Garden:Blue;Noida City Centre:Blue'])
        writer.writerow(['Noida City Centre', 'Blue', 'Noida Golf Course:Blue'])
        
        # Yellow Line stations
        writer.writerow(['HUDA City Centre', 'Yellow', 'IFFCO Chowk:Yellow'])
        writer.writerow(['IFFCO Chowk', 'Yellow', 'HUDA City Centre:Yellow;MG Road:Yellow'])
        writer.writerow(['MG Road', 'Yellow', 'IFFCO Chowk:Yellow;Sikandarpur:Yellow'])
        writer.writerow(['Sikandarpur', 'Yellow', 'MG Road:Yellow;Guru Dronacharya:Yellow'])
        writer.writerow(['Guru Dronacharya', 'Yellow', 'Sikandarpur:Yellow;Arjan Garh:Yellow'])
        writer.writerow(['Arjan Garh', 'Yellow', 'Guru Dronacharya:Yellow;Ghitorni:Yellow'])
        writer.writerow(['Ghitorni', 'Yellow', 'Arjan Garh:Yellow;Sultanpur:Yellow'])
        writer.writerow(['Sultanpur', 'Yellow', 'Ghitorni:Yellow;Chhattarpur:Yellow'])
        writer.writerow(['Chhattarpur', 'Yellow', 'Sultanpur:Yellow;Qutub Minar:Yellow'])
        writer.writerow(['Qutub Minar', 'Yellow', 'Chhattarpur:Yellow;Saket:Yellow'])
        # Saket already defined above
        writer.writerow(['Malviya Nagar', 'Yellow', 'Saket:Yellow;Hauz Khas:Yellow'])
        # Hauz Khas already defined above
        writer.writerow(['IIT', 'Yellow', 'Hauz Khas:Yellow;RK Puram:Yellow'])
        writer.writerow(['RK Puram', 'Yellow', 'IIT:Yellow;Munirka:Yellow'])
        writer.writerow(['Munirka', 'Yellow', 'RK Puram:Yellow;Vasant Vihar:Yellow'])
        writer.writerow(['Vasant Vihar', 'Yellow', 'Munirka:Yellow;Shankar Vihar:Yellow'])
        writer.writerow(['Shankar Vihar', 'Yellow', 'Vasant Vihar:Yellow;IGI Airport:Yellow'])
        writer.writerow(['IGI Airport', 'Yellow;Orange', 'Shankar Vihar:Yellow;Sadar Bazar:Yellow;Delhi Aerocity:Orange'])
        writer.writerow(['Sadar Bazar', 'Yellow', 'IGI Airport:Yellow;Palam:Yellow'])
        writer.writerow(['Palam', 'Yellow', 'Sadar Bazar:Yellow;Dashrath Puri:Yellow'])
        writer.writerow(['Dashrath Puri', 'Yellow', 'Palam:Yellow;Dabri Mor:Yellow'])
        writer.writerow(['Dabri Mor', 'Yellow', 'Dashrath Puri:Yellow;Janakpuri:Yellow'])
        writer.writerow(['Janakpuri', 'Yellow', 'Dabri Mor:Yellow;Uttam Nagar East:Yellow'])
        writer.writerow(['Uttam Nagar East', 'Yellow', 'Janakpuri:Yellow;Nawada Metro:Yellow'])
        writer.writerow(['Nawada Metro', 'Yellow', 'Uttam Nagar East:Yellow;Dwarka Mor Metro:Yellow'])
        writer.writerow(['Dwarka Mor Metro', 'Yellow', 'Nawada Metro:Yellow;Dwarka Metro:Yellow'])
        writer.writerow(['Dwarka Metro', 'Yellow', 'Dwarka Mor Metro:Yellow;Dwarka Sector 14:Yellow'])
        writer.writerow(['Dwarka Sector 14', 'Yellow', 'Dwarka Metro:Yellow;Dwarka Sector 13:Yellow'])
        writer.writerow(['Dwarka Sector 13', 'Yellow', 'Dwarka Sector 14:Yellow;Dwarka Sector 12:Yellow'])
        writer.writerow(['Dwarka Sector 12', 'Yellow', 'Dwarka Sector 13:Yellow;Dwarka Sector 11:Yellow'])
        writer.writerow(['Dwarka Sector 11', 'Yellow', 'Dwarka Sector 12:Yellow;Dwarka Sector 10:Yellow'])
        writer.writerow(['Dwarka Sector 10', 'Yellow', 'Dwarka Sector 11:Yellow;Dwarka Sector 9:Yellow'])
        writer.writerow(['Dwarka Sector 9', 'Yellow', 'Dwarka Sector 10:Yellow;Dwarka Sector 8:Yellow'])
        writer.writerow(['Dwarka Sector 8', 'Yellow', 'Dwarka Sector 9:Yellow;Dwarka Sector 21:Yellow'])
        writer.writerow(['Dwarka Sector 21', 'Yellow', 'Dwarka Sector 8:Yellow'])
        # Continue Yellow Line from AIIMS
        writer.writerow(['Safdarjung', 'Yellow', 'AIIMS:Yellow;Jorbagh:Yellow'])
        writer.writerow(['Jorbagh', 'Yellow', 'Safdarjung:Yellow;Lok Kalyan Marg:Yellow'])
        writer.writerow(['Lok Kalyan Marg', 'Yellow', 'Jorbagh:Yellow;Udyog Bhawan:Yellow'])
        writer.writerow(['Udyog Bhawan', 'Yellow', 'Lok Kalyan Marg:Yellow;Central Secretariat:Yellow'])
        # Central Secretariat already defined above
        writer.writerow(['Palika Bazaar', 'Yellow', 'Rajiv Chowk:Yellow;RK Marg:Yellow'])
        writer.writerow(['RK Marg', 'Yellow', 'Palika Bazaar:Yellow;Rajendra Place Metro:Yellow'])
        writer.writerow(['Rajendra Place Metro', 'Yellow', 'RK Marg:Yellow;Patel Nagar Metro:Yellow'])
        writer.writerow(['Patel Nagar Metro', 'Yellow', 'Rajendra Place Metro:Yellow;Shadipur Metro:Yellow'])
        writer.writerow(['Shadipur Metro', 'Yellow', 'Patel Nagar Metro:Yellow;Kirti Nagar Metro:Yellow'])
        writer.writerow(['Kirti Nagar Metro', 'Yellow', 'Shadipur Metro:Yellow;Moti Nagar Metro:Yellow'])
        writer.writerow(['Moti Nagar Metro', 'Yellow', 'Kirti Nagar Metro:Yellow;Ramesh Nagar Metro:Yellow'])
        writer.writerow(['Ramesh Nagar Metro', 'Yellow', 'Moti Nagar Metro:Yellow;Rajouri Garden Metro:Yellow'])
        writer.writerow(['Rajouri Garden Metro', 'Yellow', 'Ramesh Nagar Metro:Yellow;Tagore Garden Metro:Yellow'])
        writer.writerow(['Tagore Garden Metro', 'Yellow', 'Rajouri Garden Metro:Yellow;Subhash Nagar Metro:Yellow'])
        writer.writerow(['Subhash Nagar Metro', 'Yellow', 'Tagore Garden Metro:Yellow;Tilak Nagar Metro:Yellow'])
        writer.writerow(['Tilak Nagar Metro', 'Yellow', 'Subhash Nagar Metro:Yellow;Janakpuri East Metro:Yellow'])
        writer.writerow(['Janakpuri East Metro', 'Yellow', 'Tilak Nagar Metro:Yellow;Janakpuri West Metro:Yellow'])
        writer.writerow(['Janakpuri West Metro', 'Yellow', 'Janakpuri East Metro:Yellow'])
        # Continue from Kashmere Gate
        writer.writerow(['Civil Lines', 'Yellow', 'Kashmere Gate:Yellow;Vidhan Sabha:Yellow'])
        writer.writerow(['Vidhan Sabha', 'Yellow', 'Civil Lines:Yellow;Vishwavidyalaya:Yellow'])
        writer.writerow(['Vishwavidyalaya', 'Yellow', 'Vidhan Sabha:Yellow;GTB Nagar:Yellow'])
        writer.writerow(['GTB Nagar', 'Yellow', 'Vishwavidyalaya:Yellow;Model Town:Yellow'])
        writer.writerow(['Model Town', 'Yellow', 'GTB Nagar:Yellow;Azadpur:Yellow'])
        writer.writerow(['Azadpur', 'Yellow;Pink', 'Model Town:Yellow;Adarsh Nagar:Yellow;Majlis Park:Pink'])
        writer.writerow(['Adarsh Nagar', 'Yellow', 'Azadpur:Yellow;Jahangirpuri:Yellow'])
        writer.writerow(['Jahangirpuri', 'Yellow', 'Adarsh Nagar:Yellow;Haiderpur:Yellow'])
        writer.writerow(['Haiderpur', 'Yellow', 'Jahangirpuri:Yellow;Rohini Sector 18:Yellow'])
        writer.writerow(['Rohini Sector 18', 'Yellow', 'Haiderpur:Yellow;Samaypur Badli:Yellow'])
        writer.writerow(['Samaypur Badli', 'Yellow', 'Rohini Sector 18:Yellow'])
        
        # Green Line stations
        writer.writerow(['Inderlok', 'Green;Red', 'Ashok Park Main:Green;Kanhaiya Nagar:Red'])
        writer.writerow(['Ashok Park Main', 'Green', 'Inderlok:Green;Punjabi Bagh:Green'])
        writer.writerow(['Punjabi Bagh', 'Green;Pink', 'Ashok Park Main:Green;Shivaji Park:Green;Punjabi Bagh West:Pink'])
        writer.writerow(['Shivaji Park', 'Green', 'Punjabi Bagh:Green;Madipur:Green'])
        writer.writerow(['Madipur', 'Green', 'Shivaji Park:Green;Paschim Vihar East:Green'])
        writer.writerow(['Paschim Vihar East', 'Green', 'Madipur:Green;Paschim Vihar West:Green'])
        writer.writerow(['Paschim Vihar West', 'Green', 'Paschim Vihar East:Green;Peeragarhi:Green'])
        writer.writerow(['Peeragarhi', 'Green', 'Paschim Vihar West:Green;Udyog Nagar:Green'])
        writer.writerow(['Udyog Nagar', 'Green', 'Peeragarhi:Green;Maharaja Surajmal:Green'])
        writer.writerow(['Maharaja Surajmal', 'Green', 'Udyog Nagar:Green;Nangloi:Green'])
        writer.writerow(['Nangloi', 'Green', 'Maharaja Surajmal:Green;Nangloi Railway:Green'])
        writer.writerow(['Nangloi Railway', 'Green', 'Nangloi:Green;Rajdhani Park:Green'])
        writer.writerow(['Rajdhani Park', 'Green', 'Nangloi Railway:Green;Mundka:Green'])
        writer.writerow(['Mundka', 'Green', 'Rajdhani Park:Green;Mundka Industrial:Green'])
        writer.writerow(['Mundka Industrial', 'Green', 'Mundka:Green;Ghevra:Green'])
        writer.writerow(['Ghevra', 'Green', 'Mundka Industrial:Green;Tikri Kalan:Green'])
        writer.writerow(['Tikri Kalan', 'Green', 'Ghevra:Green;Tikri Border:Green'])
        writer.writerow(['Tikri Border', 'Green', 'Tikri Kalan:Green;Pandit Shree Ram:Green'])
        writer.writerow(['Pandit Shree Ram', 'Green', 'Tikri Border:Green;Bahadurgarh City:Green'])
        writer.writerow(['Bahadurgarh City', 'Green', 'Pandit Shree Ram:Green;Brigadier HS Bedi:Green'])
        writer.writerow(['Brigadier HS Bedi', 'Green', 'Bahadurgarh City:Green'])
        # Continue from Kirti Nagar
        writer.writerow(['Satguru Ram Singh', 'Green', 'Kirti Nagar:Green;Ashok Park:Green'])
        writer.writerow(['Ashok Park', 'Green', 'Satguru Ram Singh:Green'])
        
        # Pink Line stations
        writer.writerow(['Majlis Park', 'Pink', 'Azadpur:Pink;Shalimar Bagh:Pink'])
        writer.writerow(['Shalimar Bagh', 'Pink', 'Majlis Park:Pink;Netaji Subhash Place:Pink'])
        writer.writerow(['Netaji Subhash Place', 'Pink;Red', 'Shalimar Bagh:Pink;Shakurpur:Pink;Kohat Enclave:Red'])
        writer.writerow(['Shakurpur', 'Pink', 'Netaji Subhash Place:Pink;Punjabi Bagh West:Pink'])
        writer.writerow(['Punjabi Bagh West', 'Pink', 'Shakurpur:Pink;Punjabi Bagh:Pink'])
        # Punjabi Bagh already defined above
        writer.writerow(['ESI Hospital', 'Pink', 'Punjabi Bagh:Pink;Rajouri Garden:Pink'])
        # Rajouri Garden already defined above
        writer.writerow(['Mayapuri', 'Pink', 'Rajouri Garden:Pink;Naraina Vihar:Pink'])
        writer.writerow(['Naraina Vihar', 'Pink', 'Mayapuri:Pink;Delhi Cantt:Pink'])
        writer.writerow(['Delhi Cantt', 'Pink;Orange', 'Naraina Vihar:Pink;Durgabai Deshmukh:Pink;Delhi Cantt Airport:Orange'])
        writer.writerow(['Durgabai Deshmukh', 'Pink', 'Delhi Cantt:Pink;Sir Vishweshwaraiah:Pink'])
        writer.writerow(['Sir Vishweshwaraiah', 'Pink', 'Durgabai Deshmukh:Pink;Bhikaji Cama:Pink'])
        writer.writerow(['Bhikaji Cama', 'Pink', 'Sir Vishweshwaraiah:Pink;Sarojini Nagar:Pink'])
        writer.writerow(['Sarojini Nagar', 'Pink', 'Bhikaji Cama:Pink;INA Pink:Pink'])
        writer.writerow(['INA Pink', 'Pink', 'Sarojini Nagar:Pink;South Extension:Pink'])
        writer.writerow(['South Extension', 'Pink', 'INA Pink:Pink;Lajpat Nagar:Pink'])
        writer.writerow(['Lajpat Nagar', 'Pink;Violet', 'South Extension:Pink;Vinobapuri:Pink;Moolchand:Violet'])
        writer.writerow(['Vinobapuri', 'Pink', 'Lajpat Nagar:Pink;Ashram:Pink'])
        writer.writerow(['Ashram', 'Pink', 'Vinobapuri:Pink;Hazrat Nizamuddin:Pink'])
        writer.writerow(['Hazrat Nizamuddin', 'Pink', 'Ashram:Pink;Mayur Vihar Pocket:Pink'])
        writer.writerow(['Mayur Vihar Pocket', 'Pink', 'Hazrat Nizamuddin:Pink;Mayur Vihar:Pink'])
        # Mayur Vihar already defined above
        writer.writerow(['Trilokpuri', 'Pink', 'Mayur Vihar:Pink;East Vinod Nagar:Pink'])
        writer.writerow(['East Vinod Nagar', 'Pink', 'Trilokpuri:Pink;Mandawali:Pink'])
        writer.writerow(['Mandawali', 'Pink', 'East Vinod Nagar:Pink;IP Extension:Pink'])
        writer.writerow(['IP Extension', 'Pink', 'Mandawali:Pink;Anand Vihar:Pink'])
        writer.writerow(['Anand Vihar', 'Pink;Blue', 'IP Extension:Pink;Karkardooma:Pink;Anand Vihar ISBT:Blue'])
        writer.writerow(['Karkardooma', 'Pink;Blue', 'Anand Vihar:Pink;Karkardooma Court:Pink;Karkardooma Metro:Blue'])
        writer.writerow(['Karkardooma Court', 'Pink', 'Karkardooma:Pink;Krishna Nagar:Pink'])
        writer.writerow(['Krishna Nagar', 'Pink', 'Karkardooma Court:Pink;East Azad Nagar:Pink'])
        writer.writerow(['East Azad Nagar', 'Pink', 'Krishna Nagar:Pink;Welcome Pink:Pink'])
        writer.writerow(['Welcome Pink', 'Pink', 'East Azad Nagar:Pink;Jaffrabad:Pink'])
        writer.writerow(['Jaffrabad', 'Pink', 'Welcome Pink:Pink;Maujpur:Pink'])
        writer.writerow(['Maujpur', 'Pink', 'Jaffrabad:Pink;Gokulpuri:Pink'])
        writer.writerow(['Gokulpuri', 'Pink', 'Maujpur:Pink;Johri Enclave:Pink'])
        writer.writerow(['Johri Enclave', 'Pink', 'Gokulpuri:Pink;Shiv Vihar:Pink'])
        writer.writerow(['Shiv Vihar', 'Pink', 'Johri Enclave:Pink'])
        
        # Orange Line stations (Airport Express)
        writer.writerow(['New Delhi Railway', 'Orange', 'New Delhi:Orange;Shivaji Stadium:Orange'])
        writer.writerow(['Shivaji Stadium', 'Orange', 'New Delhi Railway:Orange;New Delhi:Orange;Dhaula Kuan:Orange'])
        writer.writerow(['Dhaula Kuan', 'Orange', 'Shivaji Stadium:Orange;Delhi Aerocity:Orange'])
        writer.writerow(['Delhi Aerocity', 'Orange', 'Dhaula Kuan:Orange;IGI Airport:Orange'])
        # IGI Airport already defined above
        writer.writerow(['Delhi Cantt Airport', 'Orange', 'Delhi Cantt:Orange;Dwarka Sector 21 Airport:Orange'])
        writer.writerow(['Dwarka Sector 21 Airport', 'Orange', 'Delhi Cantt Airport:Orange'])
        
        # Violet Line stations
        writer.writerow(['Kashmere Gate Violet', 'Violet', 'Lal Quila:Violet'])
        writer.writerow(['Lal Quila', 'Violet', 'Kashmere Gate Violet:Violet;Jama Masjid:Violet'])
        writer.writerow(['Jama Masjid', 'Violet', 'Lal Quila:Violet;Delhi Gate:Violet'])
        writer.writerow(['Delhi Gate', 'Violet', 'Jama Masjid:Violet;ITO:Violet'])
        writer.writerow(['ITO', 'Violet', 'Delhi Gate:Violet;Mandi House:Violet'])
        # Mandi House already defined above
        writer.writerow(['Janpath', 'Violet', 'Mandi House:Violet;Central Secretariat Violet:Violet'])
        writer.writerow(['Central Secretariat Violet', 'Violet', 'Janpath:Violet;Khan Market:Violet'])
        writer.writerow(['Khan Market', 'Violet', 'Central Secretariat Violet:Violet;JLN Stadium:Violet'])
        writer.writerow(['JLN Stadium', 'Violet', 'Khan Market:Violet;Jangpura:Violet'])
        writer.writerow(['Jangpura', 'Violet', 'JLN Stadium:Violet;Lajpat Nagar:Violet'])
        # Lajpat Nagar already defined above
        writer.writerow(['Moolchand', 'Violet', 'Lajpat Nagar:Violet;Kailash Colony:Violet'])
        writer.writerow(['Kailash Colony', 'Violet', 'Moolchand:Violet;Nehru Place:Violet'])
        writer.writerow(['Nehru Place', 'Violet', 'Kailash Colony:Violet;Kalkaji Mandir:Violet'])
        writer.writerow(['Kalkaji Mandir', 'Violet;Magenta', 'Nehru Place:Violet;Govindpuri:Violet;Kalkaji:Magenta'])
        writer.writerow(['Govindpuri', 'Violet', 'Kalkaji Mandir:Violet;Harkesh Nagar:Violet'])
        writer.writerow(['Harkesh Nagar', 'Violet', 'Govindpuri:Violet;Jasola Apollo:Violet'])
        writer.writerow(['Jasola Apollo', 'Violet', 'Harkesh Nagar:Violet;Sarita Vihar:Violet'])
        writer.writerow(['Sarita Vihar', 'Violet', 'Jasola Apollo:Violet;Mohan Estate:Violet'])
        writer.writerow(['Mohan Estate', 'Violet', 'Sarita Vihar:Violet;Tughlakabad:Violet'])
        writer.writerow(['Tughlakabad', 'Violet', 'Mohan Estate:Violet;Badarpur:Violet'])
        writer.writerow(['Badarpur', 'Violet', 'Tughlakabad:Violet;Sarai:Violet'])
        writer.writerow(['Sarai', 'Violet', 'Badarpur:Violet;NHPC Chowk:Violet'])
        writer.writerow(['NHPC Chowk', 'Violet', 'Sarai:Violet;Mewala:Violet'])
        writer.writerow(['Mewala', 'Violet', 'NHPC Chowk:Violet;Sector 28:Violet'])
        writer.writerow(['Sector 28', 'Violet', 'Mewala:Violet;Badkal Mor:Violet'])
        writer.writerow(['Badkal Mor', 'Violet', 'Sector 28:Violet;Old Faridabad:Violet'])
        writer.writerow(['Old Faridabad', 'Violet', 'Badkal Mor:Violet;Neelam Chowk:Violet'])
        writer.writerow(['Neelam Chowk', 'Violet', 'Old Faridabad:Violet;Bata Chowk:Violet'])
        writer.writerow(['Bata Chowk', 'Violet', 'Neelam Chowk:Violet;Escorts Mujesar:Violet'])
        writer.writerow(['Escorts Mujesar', 'Violet', 'Bata Chowk:Violet;Sant Surdas:Violet'])
        writer.writerow(['Sant Surdas', 'Violet', 'Escorts Mujesar:Violet;Raja Nahar Singh:Violet'])
        writer.writerow(['Raja Nahar Singh', 'Violet', 'Sant Surdas:Violet'])
        
        # Magenta Line stations
        writer.writerow(['Janakpuri West Magenta', 'Magenta', 'Dabri Mor Magenta:Magenta'])
        writer.writerow(['Dabri Mor Magenta', 'Magenta', 'Janakpuri West Magenta:Magenta;Dashrath Puri Magenta:Magenta'])
        writer.writerow(['Dashrath Puri Magenta', 'Magenta', 'Dabri Mor Magenta:Magenta;Palam Magenta:Magenta'])
        writer.writerow(['Palam Magenta', 'Magenta', 'Dashrath Puri Magenta:Magenta;Sadar Bazar Magenta:Magenta'])
        writer.writerow(['Sadar Bazar Magenta', 'Magenta', 'Palam Magenta:Magenta;IGI Airport Magenta:Magenta'])
        writer.writerow(['IGI Airport Magenta', 'Magenta', 'Sadar Bazar Magenta:Magenta;Shankar Vihar Magenta:Magenta'])
        writer.writerow(['Shankar Vihar Magenta', 'Magenta', 'IGI Airport Magenta:Magenta;Vasant Vihar Magenta:Magenta'])
        writer.writerow(['Vasant Vihar Magenta', 'Magenta', 'Shankar Vihar Magenta:Magenta;Munirka Magenta:Magenta'])
        writer.writerow(['Munirka Magenta', 'Magenta', 'Vasant Vihar Magenta:Magenta;RK Puram Magenta:Magenta'])
        writer.writerow(['RK Puram Magenta', 'Magenta', 'Munirka Magenta:Magenta;IIT Magenta:Magenta'])
        writer.writerow(['IIT Magenta', 'Magenta', 'RK Puram Magenta:Magenta;Hauz Khas Magenta:Magenta'])
        writer.writerow(['Hauz Khas Magenta', 'Magenta', 'IIT Magenta:Magenta;Panchsheel:Magenta'])
        writer.writerow(['Panchsheel', 'Magenta', 'Hauz Khas Magenta:Magenta;Chirag Delhi:Magenta'])
        writer.writerow(['Chirag Delhi', 'Magenta', 'Panchsheel:Magenta;Greater Kailash:Magenta'])
        writer.writerow(['Greater Kailash', 'Magenta', 'Chirag Delhi:Magenta;Nehru Enclave:Magenta'])
        writer.writerow(['Nehru Enclave', 'Magenta', 'Greater Kailash:Magenta;Kalkaji:Magenta'])
        writer.writerow(['Kalkaji', 'Magenta', 'Nehru Enclave:Magenta;Kalkaji Mandir:Magenta'])
        # Kalkaji Mandir already defined above
        writer.writerow(['Okhla NSIC', 'Magenta', 'Kalkaji Mandir:Magenta;Sukhdev Vihar:Magenta'])
        writer.writerow(['Sukhdev Vihar', 'Magenta', 'Okhla NSIC:Magenta;Jamia Millia:Magenta'])
        writer.writerow(['Jamia Millia', 'Magenta', 'Sukhdev Vihar:Magenta;Okhla Vihar:Magenta'])
        writer.writerow(['Okhla Vihar', 'Magenta', 'Jamia Millia:Magenta;Jasola Vihar:Magenta'])
        writer.writerow(['Jasola Vihar', 'Magenta', 'Okhla Vihar:Magenta;Kalindi Kunj:Magenta'])
        writer.writerow(['Kalindi Kunj', 'Magenta', 'Jasola Vihar:Magenta;Okhla Bird Sanctuary:Magenta'])
        writer.writerow(['Okhla Bird Sanctuary', 'Magenta', 'Kalindi Kunj:Magenta;Botanical Garden:Magenta'])
        # Botanical Garden already defined above
        
        # Additional connectivity for completeness
        writer.writerow(['Kohat Enclave', 'Red', 'Netaji Subhash Place:Red;Pitampura:Red'])
        writer.writerow(['Pitampura', 'Red', 'Kohat Enclave:Red;Rohini East:Red'])
        writer.writerow(['Rohini East', 'Red', 'Pitampura:Red;Rohini West:Red'])
        writer.writerow(['Rohini West', 'Red', 'Rohini East:Red;Rithala:Red'])
        writer.writerow(['Rithala', 'Red', 'Rohini West:Red'])
        writer.writerow(['Kanhaiya Nagar', 'Red', 'Inderlok:Red;Keshav Puram:Red'])
        writer.writerow(['Keshav Puram', 'Red', 'Kanhaiya Nagar:Red'])
        writer.writerow(['Anand Vihar ISBT', 'Blue', 'Anand Vihar:Blue;Karkardooma Metro:Blue'])
        writer.writerow(['Karkardooma Metro', 'Blue', 'Anand Vihar ISBT:Blue;Karkardooma:Blue;Preet Vihar:Blue'])
        writer.writerow(['Preet Vihar', 'Blue', 'Karkardooma Metro:Blue;Nirman Vihar:Blue'])
        writer.writerow(['Nirman Vihar', 'Blue', 'Preet Vihar:Blue;Laxmi Nagar:Blue'])
        writer.writerow(['Laxmi Nagar', 'Blue', 'Nirman Vihar:Blue;Vaishali:Blue'])
        writer.writerow(['Vaishali', 'Blue', 'Laxmi Nagar:Blue;Kaushambi:Blue'])
        writer.writerow(['Kaushambi', 'Blue', 'Vaishali:Blue;Ghaziabad:Blue'])
        writer.writerow(['Ghaziabad', 'Blue', 'Kaushambi:Blue;Electronic City:Blue'])
        writer.writerow(['Electronic City', 'Blue', 'Ghaziabad:Blue'])
    
    print("✓ stations.csv reset with comprehensive metro network")


def reset_users_csv():
    """Reset the users CSV file."""
    with open('users.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['user_name'])
    print("✓ users.csv reset")


def reset_tickets_csv():
    """Reset the tickets CSV file."""
    with open('tickets.csv', 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['ticket_id', 'user_name', 'origin', 'destination', 'price', 'path', 'instructions'])
    print("✓ tickets.csv reset")


def main():
    """Main function to reset all CSV files."""
    print("\nResetting Metro System Database...")
    print("-" * 40)
    
    reset_stations_csv()
    reset_users_csv()
    reset_tickets_csv()
    
    print("-" * 40)
    print("All CSV files have been reset successfully!")
    print("\nYou can now run 'python main.py' to start the Metro Ticket System.")
    print("\nNote: The system now includes a comprehensive Delhi Metro-like network with:")
    print("  • Red Line")
    print("  • Blue Line")
    print("  • Yellow Line")
    print("  • Green Line")
    print("  • Pink Line")
    print("  • Orange Line (Airport Express)")
    print("  • Violet Line")
    print("  • Magenta Line")
    print("  • Multiple interchange stations for line changes")


if __name__ == "__main__":
    main()