# Generated by Django 4.2.7 on 2025-11-25 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("metro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetroLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="blue", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("ticket_booking_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "position",
                    models.IntegerField(
                        help_text="Position of station on the line (for ordering)"
                    ),
                ),
                ("is_interchange", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="metro.metroline",
                    ),
                ),
            ],
            options={
                "ordering": ["line", "position"],
                "unique_together": {("line", "position")},
            },
        ),
        migrations.CreateModel(
            name="StationConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[("normal", "Normal"), ("interchange", "Interchange")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "from_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_from",
                        to="metro.station",
                    ),
                ),
                (
                    "to_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_to",
                        to="metro.station",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_station", "to_station")},
            },
        ),
        migrations.CreateModel(
            name="DailyFootfall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("entry_count", models.IntegerField(default=0)),
                ("exit_count", models.IntegerField(default=0)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footfall_records",
                        to="metro.station",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "station"],
                "unique_together": {("station", "date")},
            },
        ),
    ]
